### ISSUE TITLE
Does asm-differ support AltiVec PowerPC 64?

### ISSUE THREAD

**Issue by JamesIsWack** [simonlindholm/asm-differ#124]
I'm wanting to add PS3 support to `decomp.me`, but the maintainers said I need to check if asm-differ supports it. Tried to figure it out myself but dont know how to use it correctly.

here's the command I used:
```
 python3 ../asm-differ/diff.py -f EBOOT.asm start
 ```
 output:
 ```
 Traceback (most recent call last):
  File "C:\cygwin\home\693982\asm-differ\diff.py", line 3664, in <module>
    main()
  File "C:\cygwin\home\693982\asm-differ\diff.py", line 3551, in main
    diff_settings.apply(settings, args)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'diff_settings' has no attribute 'apply'
```
dunno if im using it wrong, of if asm-differ doesnt support the instruction set. if it doesnt, i would like to know how to add support.

**Comment by simonlindholm** [comment]
Your diff_settings.py file needs an `apply` function. See the file in the repo for an example.

It's untested whether asm-differ supports AltiVec; I expect it probably does as long as you pass the right objdump flags. In any case that's unrelated to this error, and you'd only notice missing support if you tried it on a function with altivec instructions, which should be rare.
